name: Regression E2E Tests

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: write

jobs:
  E2E-Tests:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        containers: [1, 2] 
    steps:
      - name: Checkout code
        uses: actions/checkout@v4.2.2

      - name: Setup Node.js
        uses: actions/setup-node@v4.2.0
        with:
          node-version: '22.16.0'

      - name: Enable Corepack
        run: corepack enable

      - name: Configure Yarn
        working-directory: web
        run: |
          corepack prepare yarn@4.9.2 --activate
          mkdir -p .yarn/cache

      - name: Install dependencies
        working-directory: web
        run: yarn install

      - name: Run Cypress Tests
        uses: cypress-io/github-action@v6.10.0
        with:
          working-directory: web
          start: yarn dev
          wait-on: 'http://localhost:3000'
          command: yarn cy:run
          parallel: true
          record: true
        env:
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload screenshots
        if: failure()
        uses: actions/upload-artifact@v4.6.0
        with:
          name: cypress-screenshots
          path: web/cypress/screenshots/
          if-no-files-found: ignore

      - name: Upload videos
        if: always()
        uses: actions/upload-artifact@v4.6.0
        with:
          name: cypress-videos
          path: web/cypress/videos/
          if-no-files-found: ignore