name: Regression E2E Tests

on:
  workflow_dispatch:
  push:
    branches: [main]
  pull_request:
    branches: [main]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  e2e-chrome:
    uses: ./.github/workflows/e2e-runner.yml
    with:
      browser: chrome
      group: chrome
    secrets:
      CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
      BOARD_USERNAME: ${{ secrets.BOARD_USERNAME }}
      BOARD_PASSWORD: ${{ secrets.BOARD_PASSWORD }}

  e2e-firefox:
    uses: ./.github/workflows/e2e-runner.yml
    with:
      browser: firefox
      group: firefox
    secrets:
      CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
      BOARD_USERNAME: ${{ secrets.BOARD_USERNAME }}
      BOARD_PASSWORD: ${{ secrets.BOARD_PASSWORD }}
